# Use the official nginx image as base
FROM nginx:alpine

# Copy the static files to the nginx html directory
COPY estatistica.html /usr/share/nginx/html/estatistica.html
COPY tabela.html /usr/share/nginx/html/tabela.html
COPY config.js /usr/share/nginx/html/config.js
