version: '3.8'

services:
  nginx:
    build: .
    ports:
      - "83:80"
    volumes:
      - ./config.js:/usr/share/nginx/html/config.js
      - ./estatistica.html:/usr/share/nginx/html/estatistica.html
      - ./tabela.html:/usr/share/nginx/html/tabela.html
